Meshopt msvc (#3)
* build meshopt with msvc

* headers

* submodule

* update workflows

* almost works

* works

* recurse submodules

---------

Co-authored-by: phoenix mandala <phoenix.mandala@pm.me>

diff --git a/scripts/cargo-setup b/scripts/cargo-setup
--- a/scripts/cargo-setup
+++ b/scripts/cargo-setup
@@ -22,12 +22,20 @@ fi
 if [[ $BIN || $FORCE || ! -d ".bin" ]]; then
     rm -rf .bin
     mkdir .bin > /dev/null
-    ln -s /usr/bin/clang .bin/clang-cl
-    ln -s /usr/bin/llvm-ar .bin/llvm-lib
-    ln -s /usr/bin/lld-link .bin/lld-link
-    clang-cl -v;
-    llvm-lib -v;
-    lld-link --version;
+    CLANG="$(which clang-cl | which clang)"
+    LLVM_AR="$(which llvm-lib | which llvm-ar)"
+    LLD_LINK="$(which lld-link)"
+    if [[ -z $CLANG ]]; then echo "WARN: Cannot find clang!"; fi
+    if [[ -z $LLVM_AR ]]; then echo "WARN: Cannot find llvm-ar!"; fi
+    if [[ -z $LLD_LINK ]]; then echo "WARN: Cannot find lld-link!"; fi
+    ln -s "$CLANG" .bin/clang-cl
+    ln -s "$LLVM_AR" .bin/llvm-lib
+    ln -s "$LLD_LINK" .bin/lld-link
+    set -e
+    ./.bin/clang-cl -v;
+    ./.bin/llvm-lib -v;
+    ./.bin/lld-link --version;
+    set +e
 fi
 
 cat <<EOF
